#default_stages: [commit, push]
repos:
#-   repo: local
#    hooks:
#    -   id: mypy and
#        name: my_tsting
#        entry: "mypy ." & "darglint ."
#        language: python
#        types: [python]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Compliance with coding rules (maintainability-check)
        additional_dependencies: [
                "flake8-black",
                "flake8-isort",
                "pep8-naming",
                "flake8-docstrings",
                "flake8-todo",
                "flake8-requirements",
                "flake8-aaa",
                "flake8-noqa",
#                "flake8-sql",
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        name: Compliance with mypy coding rules (maintainability-check)

-   repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
    -   id: darglint
        name: Compliance with darglint coding rules (maintainability-check)

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Reusability (maintainability-check)
        additional_dependencies: [
                "cohesion",
        ]
#        exclude: '^regex_pattern$'
#        args: [--cohesion-below=80]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Complexity and Coupling (maintainability-check)
        additional_dependencies: [
                "flake8-cognitive-complexity",
                "flake8-simplify",
                "flake8-comprehensions",
        ]
#        args: [--max-cognitive-complexity=7]

