#default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Compliance with coding rules (maintainability-check)
        additional_dependencies: [
                "flake8-black",
                "flake8-isort",
                "pep8-naming",
                "flake8-docstrings",
                "flake8-todo",
                "flake8-requirements",
                "flake8-aaa",
                "flake8-noqa",
                "flake8-functions"
#                "flake8-sql",
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        name: Compliance with mypy coding rules (maintainability-check)
#        args: [--disallow-untyped-defs=True, --disallow-incomplete-defs=True, --check-untyped-defs=True]

-   repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
    -   id: darglint
        name: Compliance with darglint coding rules (maintainability-check)
#        args: [--strictness=full, --docstring_style=sphinx]

-   repo: https://github.com/regebro/pyroma
    rev: "3.2"
    hooks:
    -   id: pyroma
        name: Compliance with pyroma rules (maintainability-check)

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Reusability (maintainability-check)
        additional_dependencies: [
                "cohesion",
        ]
#        exclude: '^regex_pattern$'
#        args: [--cohesion-below=80]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: Complexity and Coupling (maintainability-check)
        additional_dependencies: [
                "flake8-cognitive-complexity",
                "flake8-simplify",
                "flake8-comprehensions",
        ]
#        args: [--max-cognitive-complexity=7]

