repos:
-   repo: https://github.com/massiwen/template
#    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: black
    -   id: isort
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
    -   id: mypy